### ISSUE TITLE
[Bug]: Missing X server or $DISPLAY inside the docker

### ISSUE THREAD

**Issue by Nefcanto** [puppeteer/puppeteer#11044]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer")

const initialize = () => {
    process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0

}

let browser = null

const launch = async () => {

    browser = await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
        ],
        executablePath: "/opt/google/chrome/chrome",
        headless: false,
        env: {
            DISPLAY: ':0.0',
        },
    })
}

(async () => {
    initialize()
    await launch()
})()
```

### Error string

Missing X server or $DISPLAY

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to run puppeteer INSIDE docker. This is my `Dockerfile`:

```
FROM node:lts-bullseye-slim

RUN echo 'export PUPPETEER_SKIP_DOWNLOAD=true' > /etc/bash.bashrc

COPY . /project

WORKDIR /project

RUN apt update \
    && npm install --location=global npm -y \
    && npm install -g npm-check

RUN cd /project \
    && npm i

RUN apt-get update && \
    apt-get install gnupg wget -y && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install google-chrome-stable -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*
```

And this is my `docker-compose.yml` to create a container based on that image:

```
version: "3.9"
services: 
    accounts:
        image: holism/crawl
        container_name: crawl
        working_dir: /project
        ports: 
            - 3000:3000
        restart: always
        command: tail -f /dev/null
        volumes:
            - /project/package.json:/project/package.json
            - /project/app.js:/project/app.js
```

Then I go into the docker using `docker exec -it crawl bash` and I run `node app.js`. I get this error:

```

/project/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262
                reject(new Error([
                       ^

Error: Failed to launch the browser process! undefined
[173:187:0927/084608.100277:ERROR:bus.cc(406)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[173:173:0927/084608.105774:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[173:173:0927/084608.105788:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/project/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at ChildProcess.emit (node:events:529:35)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

This is my `package.json`:

```
{
    "dependencies": {
        "puppeteer": "^19.7.3"
    }
}
```

### Expectation

How can I connect it to my local machine's display?

### Reality

How can I connect it to my local machine's display?

### Puppeteer version

21.3.5

### Node version

v18.18.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux
