### ISSUE TITLE
[Bug]: Not working with Amazon Linux 2023/6.0.3

### ISSUE THREAD

**Issue by rafaneri** [puppeteer/puppeteer#11697]
### Minimal, reproducible example

```JavaScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent("<p>Hello world!</p>");

  // const pageHeight = await page.evaluate(() => {
  //   return window.innerHeight;
  // });
  // const millimeters = pageHeight * (25.4 / 96);

  const buffer = await page.pdf({
    format: "A4",
    printBackground: true,
    margin: {
      left: "0px",
      top: "0px",
      right: "0px",
      bottom: "0px",
    },
  });

  await browser.close();
})();
```

### Error string

Failed to launch the browser process!\n/home/webapp/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome: /home/webapp/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome: cannot execute binary file\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

The expectation was to generate the buffer of a PDF.

### Reality

I actually receive the error:

Failed to launch the browser process!\n/home/webapp/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome: /home/webapp/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome: cannot execute binary file\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n

### Puppeteer version

21.7.0

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by OrKoN** [comment]
What is the CPU architecture on the system?

**Comment by rafaneri** [comment]
ARM 64 bits.

**Comment by OrKoN** [comment]
Currently, there are no Chrome binaries for linux arm64 available. See https://github.com/puppeteer/puppeteer/issues/7740 and https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1

**Comment by rafaneri** [comment]
But I'm trying with firefox same error. They are AWS Graviton 64-bit Arm architecture

```console
/root/pup/node_modules/@puppeteer/browsers/lib/cjs/launch.js:267
                reject(new Error([
                       ^

Error: Failed to launch the browser process!
/root/.cache/puppeteer/firefox/linux-123.0a1/firefox/firefox: /root/.cache/puppeteer/firefox/linux-123.0a1/firefox/firefox: cannot execute binary file


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/root/pup/node_modules/@puppeteer/browsers/lib/cjs/launch.js:267:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.18.2
```

**Comment by OrKoN** [comment]
I don't think Mozilla ships linux arm64 binaries either: e.g., by checking https://archive.mozilla.org/pub/firefox/nightly/2024/01/2024-01-18-09-55-36-mozilla-central/ cc @whimboo

**Comment by rafaneri** [comment]
Yeah, it's a problem. So I'm creating a new environment with x86_64 platform to try. 
I will keep in touch. 

thank you @OrKoN

**Comment by OrKoN** [comment]
Perhaps something like https://github.com/ptitSeb/box64 could emulate x64 for arm64 hosts

**Comment by rafaneri** [comment]
I will try it https://pptr.dev/troubleshooting#running-puppeteer-on-aws-ec2-instance-running-amazon-linux

**Comment by OrKoN** [comment]
Chrome needs these dependencies https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux If you have browser builds provided by Amazon Linux you can use those (if the version is compatible) and provide the path to the browser binary using the executablePath launch option.

**Comment by rafaneri** [comment]
@OrKoN and @whimboo, thank you guy's!

I did the environment change. Some adjusts in my project to successful deploy.

.puppeteerrc.cjs in root project:
```cjs
const { join } = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
    // Changes the cache location for Puppeteer.
    cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

It was needed create an *.ebextensions* folder in root project with a file *chrome_puppeteer.config* with this content:
```yaml
commands:
  chrome:
    command: sudo amazon-linux-extras install epel -y && sudo yum install -y chromium
```

And then, the EB deploy works.

**Comment by raphaelsetin** [comment]
## For others who stumble upon this (for `x64`):

I am currently using "puppeteer": "^22.4.1" and AMI `amazon/aws-elasticbeanstalk-amzn-2023.3.20240219.64bit-eb_nodejs20_amazon_linux_2023-hvm-2024-02-20T16-40`, and the solution for me was this `.ebextensions` configuration file:
```
packages:
  yum:
    libXcomposite: []
    libXdamage: []
    libXrandr: []
    libxkbcommon: []
    pango: []
    alsa-lib: []
    atk: []
    at-spi2-atk: []
    cups-libs: []
    libdrm: []
    mesa-libgbm: []
```

I also needed to install some fonts for my use case, which rendered the **additional** packages in my `.ebextensions` configuration file:
```
packages:
  yum:
    fontconfig: []
    dejavu-sans-fonts: []
    dejavu-sans-mono-fonts: []
    dejavu-serif-fonts: []
    liberation-mono-fonts: []
    liberation-sans-fonts: []
    liberation-serif-fonts: []
    google-noto-emoji-fonts: []
    google-noto-fonts-common: []
    google-noto-sans-fonts: []
    google-noto-serif-fonts: []
```
---
Even though the question is about `arm64` and not `x64`, I believe others may find this helpful.
