### ISSUE TITLE
[Bug]: ERROR: Failed to set up chrome-headless-shell v121.0.6167.85!

### ISSUE THREAD

**Issue by schmittjoaopedro** [puppeteer/puppeteer#11983]
### Error string

ERROR: Failed to set up chrome-headless-shell v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

### Background

I have a puppeteer project that I build in Github Actions to a Docker image.
Last week I was building this project fine, with no issues, but suddenly this week I started to get a puppeteer download error.

The following is my package.json:
```json
{
  "name": "puppeteer-project",
  "version": "1.0.0",
  "main": "App.js",
  "type": "module",
  "scripts": {
    "start": "node src/App.js",
    "test": "c8 mocha"
  },
  "dependencies": {
    "cors": "2.8.5",
    "express": "4.18.2",
    "moment": "2.30.1",
    "pdfkit": "0.14.0",
    "puppeteer": "21.11.0"
  },
  "devDependencies": {
    "c8": "9.1.0",
    "chai": "5.1.0",
    "fetch-mock": "9.11.0",
    "mocha": "10.3.0",
    "nyc": "15.1.0",
    "pdfreader": "3.0.2",
    "sinon": "17.0.1"
  }
}
```

The following is my Dockerfile:
```Dockerfile
FROM node:20@sha256:cb7cd40ba6483f37f791e1aace576df449fc5f75332c19ff59e2c6064797160e

# https://pptr.dev/guides/docker
# https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 dbus dbus-x11 \
      --no-install-recommends \
    && service dbus start \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r pptruser && useradd -rm -g pptruser -G audio,video pptruser

ENV DBUS_SESSION_BUS_ADDRESS autolaunch:

WORKDIR /app

COPY package.json .

RUN npm install

COPY src/* .

EXPOSE 8080

CMD [ "node", "App.js" ]
```

The following is my Github Actions:

```yaml
name: main-build

on:
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - id: checkout
        name: GIT checkout
        uses: actions/checkout@v4

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Run Tests
        run: npm test

      - id: ecr
        name: Setup ECR
        uses: ./.github/actions/ecr_setup

      - id: build
        name: Build
        env:
          DOCKER_REGISTRY: ${{ steps.ecr.outputs.docker_registry }}
          AWS_ACCESS_KEY_ID: ${{ steps.ecr.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.ecr.outputs.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ steps.ecr.outputs.aws_session_token }}
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/puppeteer-project:latest .
          docker push ${{ env.DOCKER_REGISTRY }}/puppeteer-project:latest
```

Whenever the `npm install` runs, either in the pipeline itself during the test phase (that for now I'm skipping because I'm not testing puppeteer) or the docker build phase, I get a download error.

### Expectation

I'd expect both the test-phase and docker-image to build successfully, as last week it did.

### Reality

However, I'm getting the following error:

```
#10 [5/6] RUN npm install
#10 13.53 npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#10 16.74 npm notice 
#10 16.74 npm notice New minor version of npm available! 10.1.0 -> 10.4.0
#10 16.74 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
#10 16.74 npm notice Run `npm install -g npm@10.4.0` to update!
#10 16.74 npm notice 
#10 16.74 npm ERR! code 1
#10 16.74 npm ERR! path /app/node_modules/puppeteer
#10 16.75 npm ERR! command failed
#10 16.75 npm ERR! command sh -c node install.mjs
#10 16.75 npm ERR! Error: ERROR: Failed to set up chrome-headless-shell v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
#10 16.75 npm ERR!     at file:///app/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:81:27
#10 16.75 npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#10 16.75 npm ERR!     at async Promise.all (index 1)
#10 16.75 npm ERR!     at async downloadBrowser (file:///app/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:87:9) {
#10 16.75 npm ERR!   [cause]: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chrome-headless-shell-linux64.zip
#10 16.75 npm ERR!       at file:///app/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:64:31
#10 16.75 npm ERR!       at ClientRequest.requestCallback (file:///app/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:42:13)
#10 16.75 npm ERR!       at Object.onceWrapper (node:events:629:26)
#10 16.75 npm ERR!       at ClientRequest.emit (node:events:514:28)
#10 16.75 npm ERR!       at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
#10 16.75 npm ERR!       at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
#10 16.75 npm ERR!       at TLSSocket.socketOnData (node:_http_client:535:22)
#10 16.75 npm ERR!       at TLSSocket.emit (node:events:514:28)
#10 16.75 npm ERR!       at addChunk (node:internal/streams/readable:376:12)
#10 16.75 npm ERR!       at readableAddChunk (node:internal/streams/readable:349:9)
#10 16.75 npm ERR! }
#10 16.75 
#10 16.75 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-22T18_30_51_131Z-debug-0.log
#10 ERROR: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```

### Puppeteer version

21.11.0

### Node version

20.0.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux
