### ISSUE TITLE
[Bug]: Error Capturing Screenshot in AWS Lambda - Input Directory "/var/task/bin" Does Not Exist

### ISSUE THREAD

**Issue by jacksonkasi1** [puppeteer/puppeteer#13069]
### **Minimal, Reproducible Example**

I am using `puppeteer-core` with `@sparticuz/chromium` in an AWS Lambda function to capture screenshots. When I attempt to launch Chromium in the serverless environment (AWS Lambda), I get the following error:

**chrome-script.ts**
```typescript
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

export const getChrome = async (url: string) => {
  const executablePath = await chromium.executablePath() || '/var/task/bin/chromium';

  const browser = await puppeteer.launch({
    executablePath: executablePath,
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
    ],
  });

  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle0' });

  // Trigger the screenshot
  const screenshot = await page.screenshot({ encoding: 'base64' });

  await browser.close();
  return screenshot;
};
```

**index.ts**
```typescript

import { Hono } from "hono";
import { handle } from "hono/aws-lambda";

// ** import middlewares
import { cors } from "hono/cors";
import { logger } from "hono/logger";

// ** import routes
import { getChrome } from "./config/chrome-script";


// Initialize Hono app
const app = new Hono({ strict: false });

/**
 * Middlewares
 * https://hono.dev/middleware/builtin/cors
 */
app.use("*", logger());
app.use("*", cors());


app.get("/screenshot", async (c) => {
  const url = c.req.query("url");
  
  if (!url) {
    return c.json({ error: "No URL provided" }, 400);
  }

  let page, browser, chromeInstance;

  try {
    // Use the getChrome function to launch the browser and get the page object
    const chrome = await getChrome(url);

    browser = chrome.browser;
    page = chrome.page;
    // chromeInstance = chrome.instance; // Only for serverless Chrome

    // Take a screenshot of the page
    const screenshot = await page.screenshot({ encoding: 'base64' });

    // Return the screenshot as an image with appropriate headers
    return c.body(screenshot, 200, {
      "Content-Type": "image/png",
      "Content-Disposition": 'inline; filename="screenshot.png"',
    });
  } catch (error) {
    console.error("Error capturing screenshot: ", error);
    return c.json({ error: "Failed to capture screenshot" }, 500);
  } finally {
    // Clean up the browser and page instances
    if (page) await page.close();
    if (browser) await browser.close();
    // if (chromeInstance) await chromeInstance.kill(); // Only for serverless Chrome
  }
});


// Start the server (Local or AWS Lambda)
export const handler = handle(app);

```

**serverless.yml**

```yml
service: auto-pdf-processor
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 2048
  stage: production
  timeout: 30
  environment:
    NODE_ENV: production
    VERSION: v20.0
    IS_OFFLINE: ${opt:isOffline, 'false'} # Handle local environment

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/@sparticuz/chromium/**
    - node_modules/puppeteer-core/**

custom:
  serverless-offline:
    httpPort: 5000
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: "node20"
    define: { "require.resolve": "undefined" }
    platform: "node"
    concurrency: 10


functions:
  server:
    handler: src/index.handler
    layers:
      - arn:aws:lambda:ap-south-1:xxx:layer:xxxx:x
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          
```

**package.json**

```json
{
  "name": "auto-pdf-processor",
  "version": "1.0.0",
  "description": "auto-pdf-processor lambda server",
  "author": "jacksonkasi",
  "license": "MIT",
  "main": "src/handler.ts",
  "scripts": {
    "dev": "sls offline start",
    "deploy": "sls deploy",
    "remove": "sls remove"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "devDependencies": {
    "@serverless/typescript": "^3.38.0",
    "@types/node": "^22.5.4",
    "@types/serverless": "^3.12.22",
    "serverless": "^3.39.0",
    "serverless-esbuild": "^1.52.1",
    "serverless-offline": "^13.6.0",
    "typescript": "^5.5.4"
  },
  "dependencies": {
    "@sparticuz/chromium": "^127.0.0",
    "hono": "^4.5.11",
    "puppeteer": "^23.3.0",
    "puppeteer-core": "^21.5.0"
  }
}
```

**Error Log**:
```
Error: The input directory "/var/task/bin" does not exist.
    at Chromium.executablePath (/var/task/src/index.js:4652:17)
    at getChrome (/var/task/src/index.js:85106:53)
```

### **Background**

I’ve been trying to capture screenshots in an AWS Lambda environment using `puppeteer-core` and `@sparticuz/chromium`. The function works locally with a full installation of Chrome, but fails in AWS Lambda.

I’m using a Lambda Layer for Chromium with the following setup:
- Node.js runtime: 20.x
- AWS Lambda Layer ARN: `arn:aws:lambda:ap-south-1:xxxx:layer:chromium:x`

### **Expectation**

I expected the code to launch Chromium in the AWS Lambda environment, load the provided URL, and return a screenshot in base64 format.

### **Reality**

In reality, I receive an error: `The input directory "/var/task/bin" does not exist`, which suggests that Puppeteer/Chromium is unable to find the Chromium binary in the expected location within the Lambda environment.

### **Puppeteer Configuration File (if used)**

No custom Puppeteer configuration file is being used.

### **Puppeteer Version**

`puppeteer-core`: 21.5.0

### **Node Version**

Node.js 20.x (AWS Lambda runtime)

### **Package Manager**

pnpm

### **Package Manager Version**

`9.6.7`

### **Operating System**

AWS Lambda (Serverless environment) running Node.js 20.x

**Comment by Lightning00Blade** [comment]
@jacksonkasi1 Can you run the command with env variable `DEBUG=puppeteer:*` If this is a puppeteer issue there should be a log with `Launching ` and followed by the executable path. 
Have you verified that the error is not coming from `@sparticuz/chromium`, as we the Error message suggests `Chromium.executablePath` which looks like this line `const executablePath = await chromium.executablePath() || '/var/task/bin/chromium';`

**Comment by jacksonkasi1** [comment]
@Lightning00Blade  Thank you for the quick response!

I’ve run the command with the environment variable `DEBUG=puppeteer:*` and gathered the logs. Here’s the output:

```
2024-09-11T14:56:52.965Z	8980992d-5716-4cb4-ba53-874fefaa2a44	INFO	Launching Chrome in serverless environment...

2024-09-11T14:56:52.966Z	8980992d-5716-4cb4-ba53-874fefaa2a44	ERROR	Error capturing screenshot:  Error: The input directory "/var/task/bin" does not exist.
    at Chromium.executablePath (/var/task/src/index.js:4652:17)
    at getChrome (/var/task/src/index.js:85106:53)
    at /var/task/src/index.js:85143:26
    at dispatch (/var/task/src/index.js:72798:23)
    at /var/task/src/index.js:72799:20
    at cors2 (/var/task/src/index.js:73957:11)
    at dispatch (/var/task/src/index.js:72798:23)
    at /var/task/src/index.js:72799:20
    at logger2 (/var/task/src/index.js:74002:11)
    at dispatch (/var/task/src/index.js:72798:23)
```

It seems that the error is indeed coming from `@sparticuz/chromium` rather than Puppeteer, as the error points to this line:

```typescript
const executablePath = await chromium.executablePath() || '/var/task/bin/chromium';
```

This suggests that `chromium.executablePath()` is not resolving correctly in the AWS Lambda environment.

I have raised the issue with the `@sparticuz/chromium` team as well, which can be followed here:  
[Sparticuz/chromium Issue #297](https://github.com/Sparticuz/chromium/issues/297#issuecomment-2343701184).

Thank you again for your assistance! I’ll update both issues as I get more information. Let me know if there’s anything else you think could be worth trying in the meantime.

**Comment by jacksonkasi1** [comment]
@Lightning00Blade , thanks for your feedback! I've made some updates to my setup and code to resolve the issue. Here's what I did:

### Changes Made:
- **Increased memory**: Updated `serverless.yml` to allocate 3072 MB of memory and set a 60-second timeout.
- **Chromium inclusion**: I manually included the Chromium binary in the package by adding `bin/**` to the `include` section of `serverless.yml`.
- **Updated Chrome launch configuration**: In the `chrome-script.ts` file, I updated the Puppeteer launch configuration to use `chromium.args` for the necessary flags.

Here’s the updated code:

```yaml
# serverless.yml
service: auto-pdf-processor
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 3072
  timeout: 60
  environment:
    NODE_ENV: production
    VERSION: v20.0
    IS_OFFLINE: ${opt:isOffline, 'false'}
    DEBUG: puppeteer:*

package:
  exclude:
    - node_modules/**
  include:
    - bin/**  # Include the Chromium binary
```

```typescript
// chrome-script.ts
import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';

export const getChrome = async (url: string) => {
  let browser = null;

  try {
    console.log("Launching Chrome in serverless environment...");
    const executablePath = await chromium.executablePath();
    console.log(`🚀 Executable path: ${executablePath}`);

    browser = await puppeteer.launch({
      executablePath,
      headless: true,
      args: chromium.args,
    });

    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle0' });

    return { browser, page };
  } catch (error) {
    console.error("Error launching Chrome:", error);
    throw error;
  } finally {
    if (browser) await browser.close();
  }
};
```

```typescript

import { Hono } from "hono";
import { handle } from "hono/aws-lambda";

// ** import middlewares
import { cors } from "hono/cors";
import { logger } from "hono/logger";

import { getChrome } from "./config/chrome-script";

/**
 * Middlewares
 * https://hono.dev/middleware/builtin/cors
 */
app.use("*", logger());
app.use("*", cors());


app.get("/screenshot", async (c) => {
  const url = c.req.query("url");
  
  if (!url) {
    return c.json({ error: "No URL provided" }, 400);
  }

  let page, browser, chromeInstance;

  try {
    // Use the getChrome function to launch the browser and get the page object
    const chrome = await getChrome(url);

    browser = chrome.browser;
    page = chrome.page;

    // Take a screenshot of the page, base64 encoded
    const screenshot = await page.screenshot({ encoding: 'base64' });

    if (!screenshot) {
      throw new Error("Screenshot failed to capture");
    }

    console.log("Screenshot captured successfully");

    // Return the screenshot as an image with appropriate headers
    return c.body(screenshot, 200, {
      "Content-Type": "image/png",
      "Content-Disposition": 'inline; filename="screenshot.png"',
    });
  } catch (error) {
    console.error("Error capturing screenshot: ", error);
    return c.json({ error: "Failed to capture screenshot" }, 500);
  } finally {
    // Clean up the browser and page instances
    if (page) await page.close();
    if (browser) await browser.close();
  }
});


// Start the server (Local or AWS Lambda)
export const handler = handle(app);

```

```json
{
  "name": "auto-pdf-processor",
  "version": "1.0.0",
  "description": "auto-pdf-processor lambda server",
  "author": "jacksonkasi",
  "license": "MIT",
  "main": "src/handler.ts",
  "scripts": {
    "dev": "sls offline start",
    "deploy": "sls deploy",
    "remove": "sls remove"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "devDependencies": {
    "@serverless/typescript": "^3.38.0",
    "@sparticuz/chromium": "^127.0.0",
    "@types/node": "^22.5.4",
    "@types/serverless": "^3.12.22",
    "serverless": "^3.39.0",
    "serverless-esbuild": "^1.52.1",
    "serverless-offline": "^13.6.0",
    "typescript": "^5.5.4"
  },
  "dependencies": {
    "hono": "^4.5.11",
    "puppeteer": "^23.3.0",
    "puppeteer-core": "^23.3.0"
  }
}
```

### Logs:

```plaintext
2024-09-11T16:17:22.935Z INFO Launching Chrome in serverless environment...
2024-09-11T16:17:24.851Z INFO 🚀 Executable path: /tmp/chromium

puppeteer:browsers:launcher Launching /tmp/chromium --allow-pre-commit-input --disable-background-networking --disable-dev-shm-usage --disable-setuid-sandbox --disable-gpu --window-size=1920,1080 ...

puppeteer:browsers:launcher Browser process 13 onExit

ERROR Error capturing screenshot: TargetCloseError: Protocol error (Page.bringToFront): Session closed. Most likely the page has been closed.
```

### Current Issue:
The executable path is correctly resolving to `/tmp/chromium`, and Puppeteer is attempting to launch it. However, I'm still encountering a `TargetCloseError`, which indicates that the browser process is closing unexpectedly, likely due to resource limitations or something else in the serverless environment.

The error occurs when the screenshot is being captured. Is there anything specific with how Chromium is being handled in serverless environments that might be causing this abrupt termination? Could this be a Chromium compatibility issue or something I need to adjust further in the launch arguments?

Thanks again for your help!
