### ISSUE TITLE
WaitForNavigation doesn't work with data URI background

### ISSUE THREAD

**Issue by talyuk** [puppeteer/puppeteer#1399]
Hi guys! I have html page with external css which includes data URI background in some blocks.
```css
&__remove {
    position: absolute;
    right: 30px;
    top: 50%;
    margin-top: -10px;
    width: 21px;
    height: 20px;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='21' height='20' viewBox='0 0 21 20'%3E%3Cg fill='none' fill-rule='evenodd' stroke='%23979797' transform='translate%281%29' opacity='.769'%3E%3Cpath d='M19.4959677,0.430947581 L0.0269062051,19.9000091'/%3E%3Cpath d='M19.4959677,0.430947581 L0.0269062051,19.9000091' transform='matrix%28-1 0 0 1 19.523 0%29'/%3E%3C/g%3E%3C/svg%3E");
    z-index: 2;
  }
```
 I use setContent and then I need to make screenshot + pdf. 
I used puppeteer 0.12, waitForNavigation 'networkidle' worked fine (for css and other resources), I also tried to catch loading this background with interception, I saw this base64 encoded uri.  I updated puppeteer to version 0.13, and now I can't make screenshot or pdf, because waitForNavigation doesn't work with any of options (load, networkidle0, networkidle1), page just waiting for max timeout and then my script is getting broken. 

node 8.9.1
puppeteer 0.13
