### ISSUE TITLE
PDF - Header and footer font size too big

### ISSUE THREAD

**Issue by medez** [puppeteer/puppeteer#2104]
Hi, 

I'm rendering a PDF from an HTML file, and it find the header and footer font sizes bigger than in the page content. 

For example, if I set the property font-size: 12pt in a span in the content and in another one in the page footer, in the generated PDF, the two span does not have the same font-size. 

Regards

**Comment by medez** [comment]
Hi, 

I finally found a workaround : Apply the following CSS, it works
```css
#header, #footer {
  transform: scale(0.7); 
  transform-origin: top left;
}
```
