### ISSUE TITLE
Puppeteer Travis-CI chrome-headless not working

### ISSUE THREAD

**Issue by maciossek** [puppeteer/puppeteer#2674]
Posted this on Stackoverflow, too: https://stackoverflow.com/questions/50682848/puppeteer-travis-ci-chrome-headless-not-working

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: TravisCI Trusty
* URLs: https://travis-ci.com/maciossek/hft-asgmt-html-01/jobs/127338669/config and https://github.com/maciossek/hft-asgmt-html-01
* Node.js version: 9

**What steps will reproduce the problem?**

```yaml
{
  "os": "linux",
  "dist": "stable",
  "sudo": "required",
  "cache": {
    "yarn": true,
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "addons": {
    "apt": {
      "packages": [
        "gconf-service",
        "libasound2",
        "libatk1.0-0",
        "libc6",
        "libcairo2",
        "libcups2",
        "libdbus-1-3",
        "libexpat1",
        "libfontconfig1",
        "libgcc1",
        "libgconf-2-4",
        "libgdk-pixbuf2.0-0",
        "libglib2.0-0",
        "libgtk-3-0",
        "libnspr4",
        "libpango-1.0-0",
        "libpangocairo-1.0-0",
        "libstdc++6",
        "libx11-6",
        "libx11-xcb1",
        "libxcb1",
        "libxcomposite1",
        "libxcursor1",
        "libxdamage1",
        "libxext6",
        "libxfixes3",
        "libxi6",
        "libxrandr2",
        "libxrender1",
        "libxss1",
        "libxtst6",
        "ca-certificates",
        "fonts-liberation",
        "libappindicator1",
        "libnss3",
        "lsb-release",
        "xdg-utils",
        "wget"
      ]
    },
    "chrome": "stable"
  },
  "script": [
    "yarn test"
  ],
  "install": [
    "yarn install"
  ],
  "node_js": "9",
  "language": "node_js",
  "before_install": [
    "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  ]
}
```

```js
describe('Index HTML', () => {
  beforeAll(async () => {
    browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    page = await browser.newPage();
    await page.setViewport({ width, height });
  });
  afterAll(async () => {
    await page.screenshot({path: 'webpage.png'});
    browser.close();
  });

  it('Shuld have <ul> Elements', async () => {
    await page.goto(webpage);
    const ulElements = await page.evaluate(() => document.querySelector('ul').children.length);
    expect(ulElements).toBeGreaterThan(0);
  });
});
```

**What is the expected result?**
Chrome should start but doesn't on TravisCI. Works perfectly locally though.

**Comment by maciossek** [comment]
This yml worked for travis:

```yml
language: node_js
node_js:
  - "9"
dist: trusty
sudo: false  
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
```

**Comment by stevenvachon** [comment]
Works fine for me with this config:

```js
puppeteer.launch({args: ['--no-sandbox']});
```
```yml
language: node_js
node_js:
  - 6
  - 8
  - node
script: npm test
```

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci

**Comment by tastafur** [comment]
I am having this problem

```
  test navigation webapp
  0 passing (1s)
    1) "before all" hook
```

### Tell us about your environment:

Puppeteer version: 1.8.0
Platform / OS version: TravisCI Trusty
Node.js version: 8
Travis build: https://travis-ci.com/tastafur/ci-client/jobs/147082861

### What steps will reproduce the problem?
```json
{
  "os": "linux",
  "dist": "trusty",
  "sudo": true,
  "cache": {
    "yarn": true,
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "stage": "test",
  "addons": {
    "chrome": "stable"
  },
  "script": [
    "yarn test:e2e"
  ],
  "stages": [
    "validation",
    "test",
    "deploy"
  ],
  "language": "node_js",
  "before_script": [
    "yarn start &"
  ],
  "before_install": [
    null,
    "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &"
  ]
}
```

```javascript
describe('test navigation webapp', () => {
  let page;

  before (async () => {
    page = await browser.newPage();
    await page.goto('http://localhost:8080');
  });

  after (async () => {
    await page.close();
  });

  beforeEach (async () => {
    await page.waitFor(1500);
  });


  it('should find button android and click', async () => {
    const BUTTON_ANDROID_SELECTOR = '.button-0';

    await page.waitFor(BUTTON_ANDROID_SELECTOR);

    const buttonElement = await page.$(BUTTON_ANDROID_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });

  it('should find button back and return to list view', async () => {
    const BUTTON_BACK_SELECTOR = '.button-back';

    await page.waitFor(BUTTON_BACK_SELECTOR);

    const buttonElement = await page.$(BUTTON_BACK_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });

  it('should find button iOS and click', async () => {
    const BUTTON_IOS_SELECTOR = '.button-1';

    await page.waitFor(BUTTON_IOS_SELECTOR);

    const buttonElement = await page.$(BUTTON_IOS_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });
});
```

```yml
language: node_js
sudo: true
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
stages:
  - validation
  - test
jobs:
  include:
    - stage: validation
      script: npm run lint
    - stage: test
      addons:
        chrome: stable
      before_install:
        - # start your web application and listen on `localhost`
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &
      before_script:
        - yarn start &
      script:
        - yarn test:e2e
```
