### ISSUE TITLE
Page.pdf - Colors rendering

### ISSUE THREAD

**Issue by gary149** [puppeteer/puppeteer#2685]
When I run my page in headless mode every colors is rendered right.
But when I get the pdf with page.pdf() with no options some colors (a few in fact) are wrong - too bright or too dark - Is there any reason for this?

update: I solved this with this css (not sure why it wasn't working without it)

```css
html {
  -webkit-print-color-adjust: exact;
}
```
