### ISSUE TITLE
Puppeteer Travis-CI chrome-headless not working

### ISSUE THREAD

**Issue by tastafur** [puppeteer/puppeteer#3284]
I am having this problem

```
  test navigation webapp
  0 passing (1s)
    1) "before all" hook
```

### Tell us about your environment:

Puppeteer version: 1.8.0
Platform / OS version: TravisCI Trusty
Node.js version: 8
Travis build: https://travis-ci.com/tastafur/ci-client/jobs/147082861

### What steps will reproduce the problem?
```json
{
  "os": "linux",
  "dist": "trusty",
  "sudo": true,
  "cache": {
    "yarn": true,
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "stage": "test",
  "addons": {
    "chrome": "stable"
  },
  "script": [
    "yarn test:e2e"
  ],
  "stages": [
    "validation",
    "test",
    "deploy"
  ],
  "language": "node_js",
  "before_script": [
    "yarn start &"
  ],
  "before_install": [
    null,
    "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &"
  ]
}
```

```javascript
describe('test navigation webapp', () => {
  let page;

  before (async () => {
    page = await browser.newPage();
    await page.goto('http://localhost:8080');
  });

  after (async () => {
    await page.close();
  });

  beforeEach (async () => {
    await page.waitFor(1500);
  });


  it('should find button android and click', async () => {
    const BUTTON_ANDROID_SELECTOR = '.button-0';

    await page.waitFor(BUTTON_ANDROID_SELECTOR);

    const buttonElement = await page.$(BUTTON_ANDROID_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });

  it('should find button back and return to list view', async () => {
    const BUTTON_BACK_SELECTOR = '.button-back';

    await page.waitFor(BUTTON_BACK_SELECTOR);

    const buttonElement = await page.$(BUTTON_BACK_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });

  it('should find button iOS and click', async () => {
    const BUTTON_IOS_SELECTOR = '.button-1';

    await page.waitFor(BUTTON_IOS_SELECTOR);

    const buttonElement = await page.$(BUTTON_IOS_SELECTOR);

    expect(buttonElement).to.not.be.null;

    await buttonElement.click();
  });
});
```

```yml
language: node_js
sudo: true
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
stages:
  - validation
  - test
jobs:
  include:
    - stage: validation
      script: npm run lint
    - stage: test
      addons:
        chrome: stable
      before_install:
        - # start your web application and listen on `localhost`
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &
      before_script:
        - yarn start &
      script:
        - yarn test:e2e
```

**Comment by bennycode** [comment]
I also cannot get **Puppeteer** to work on Travis CI. 

I want to use it inside of my Jasmine test specification and it runs just fine locally but when I execute the same test on Travis CI, then the build gets killed because the tests don't produce any output:

> Randomized with seed 00647
Started
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
[1004/094636.814098:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.
>
> DevTools listening on ws://127.0.0.1:43459/devtools/browser/66a02882-4256-4cb8-9709-28f979b636f6
>
>No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
>
>The build has been terminated

I was reading [Medium articles](https://medium.com/@palmer_todd/thanks-for-mentioning-puppeteer-currently-in-my-travis-ci-environment-i-use-this-9d17b1e50e9f), [Stack Overflow answers](https://stackoverflow.com/a/50699254/451634) and [GitHub comments](https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-322852784) but I can't get it to work. My current setup follows best practices from @aslushnikov and @paulirish but it still doesn't want to run properly.

**.travis.yml**

```yml
dist: trusty
sudo: required

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty, taken from:
      # https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/.travis.yml#L7
      - libnss3

language: node_js
node_js:
  - "8.11.3" # Latest Node.js version supported on AWS Elastic Beanstalk

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email: false

script:
  - yarn test
```

**ServerSpec.js**

```js
const puppeteer = require('puppeteer');
const {Server} = require('../../dist/Server');
const {config} = require('../../dist/ServerConfig');

describe('End-to-End tests', () => {
  let browser = undefined;
  let server = undefined;

  beforeEach(async () => {
    // https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/docs/troubleshooting.md#running-puppeteer-on-travis-ci
    // https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-322852784
    browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox'], dumpio: true});
    server = new Server(config);
  });

  afterEach(async () => {
    if (browser) {
      await browser.close();
    }

    if (server) {
      await server.stop();
    }
  });

  describe('Homepage', () => {
    it('responds to HTTP requests', async () => {
      const port = await server.start();
      const page = await browser.newPage();
      await page.goto(`http://localhost:${port}/`);
      const pageTitle = await page.title();
      expect(pageTitle).toBe('The most secure collaboration platform · Wire');
    });
  });
});
```

Am I missing something important in my configuration? Using **puppeteer v1.8.0** with **Node.js v8.11.3**.
