### ISSUE TITLE
PDF: Footer is only shown on first and last page

### ISSUE THREAD

**Issue by konstantinkreft** [puppeteer/puppeteer#3515]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: macOS 10.13.6
* URLs (if applicable): https://github.com/kreftk/pptr-footer-bug
* Node.js version: v8.12.0

**What steps will reproduce the problem?**

_I created a repo with a minimal reproducible example._

1. `git clone https://github.com/kreftk/pptr-footer-bug.git`
2. `npm install`
3. `npm run start`
4. Inspect the created `test.pdf`

Critical code:

```css
    @page {
        size: A4 portrait;
        margin-top: 50px;
        margin-right: 0;
        margin-bottom: 50px;
        margin-left: 0;
        -webkit-print-color-adjust: exact;
    }
    @page:first {
        margin-top: 0;
    }
```

**What is the expected result?**

When deactivating the `header` through `css` for the first page, the provided `footer` should be shown on every generated pdf page.

**What happens instead?**

The `footer` is only shown on the first and the last generated pdf page.
