### ISSUE TITLE
Puppeteer ignores some CSS rules to print PDF when I used the @media print 

### ISSUE THREAD

**Issue by Kaol-Fu** [puppeteer/puppeteer#3724]
* Puppeteer version: 1.11
* Platform / OS version: Win10/CentOS7
* Node.js version: 10.15.0

**What steps will reproduce the problem?**
Set some CSS rules in @media print, then print the html to pdf. You can find some element's CSS rules are ignored by Puppeteer.

Here is my CSS codes:
```CSS
@media print {
    /* @page {
        size:"A4"
    } */
     .flipbook-viewport .flipbook{
		width: 794px!important;
		height: 1123px!important;
		max-height: 1123px;
        max-width: 794px;
        background-color: red;
    }

    .right-01 .image {
        width: 92%;
        background-repeat: no-repeat;
        background-size: 100%;
        background-image: url('../image/content/XXX.png');
        height: 920px;
        /* width: 740px; */
        margin-top: 0.8rem;
    }
}
```
You can notice that I set a background-color to check the test result. In my test, when I executed puppeteer with page.emulateMedia('print'), the flipbook-viewport and flipbook's rules work fine. But the right-01 and image's didn't work. 
But the funny thing is when I used the @media screen (also change the page.emulateMedia to screen) with the same rules, they all worked fine. So I think it might have some problem with puppeteer.

**What is the expected result?**
[good.pdf](http://www.kaol.org/wp-content/uploads/2019/01/good.pdf)

**What happens instead?**
[wrong.pdf](http://www.kaol.org/wp-content/uploads/2019/01/test.pdf)
