### ISSUE TITLE
Chromium stopped working in Alpine Docker Gitlab

### ISSUE THREAD

**Issue by ThePeach** [puppeteer/puppeteer#3740]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Alpine Linux v3.8 within Docker (`node:alpine`) GitLab CI
* URLs (if applicable): -
* Node.js version: 11.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm install puppeteer`
2. `npm test`

**What is the expected result?**

the tests are running within headless chromium 

**What happens instead?**

The following error occurs:

```
(95/95) Installing chromium@edge (71.0.3578.98-r2)
[...]

(node:104) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
(node:104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[...]

    Chromium revision is not downloaded. Run "npm install" or "yarn install"

      at Launcher.launch (node_modules/puppeteer/lib/Launcher.js:115:15)
```

**Notes**

After puppeteer refused to work with the bundled chromium (`ENOENT` error), 
as suggested in https://github.com/GoogleChrome/puppeteer/issues/379#issuecomment-437688436, thread linked from the [main official troubleshooting documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), I've decided to use the system-installed chromium with the following configuration snippet:

```
// gitlab-ci:yaml
image: node:alpine

variables:
  IS_CI: "true"

[...]

test:
    stage: test
    script:
        - echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && apk add --no-cache chromium@edge nss@edge harfbuzz@edge
        - npm test
    dependencies:
        - prepare
    artifacts:
        paths:
        - coverage
    only:
        - branches
        - tags
    variables:
        CHROME_BIN: '/usr/bin/chromium-browser'
```

```
// package.json
{
  "devDependencies": {
    "jest": "^23.6.0",
    "jest-puppeteer": "3.7.0",
    "puppeteer": "^1.11.0"
  }
}
```

```
// jest-puppeteer.config.js
const defaultConfig = {
  launch: {
    args: ['--no-sandbox']
  }
};

if (process.env.IS_CI) {
  defaultConfig.launch.executablePath = '/usr/bin/chromium-browser';
  defaultConfig.launch.args = ['--disable-dev-shm-usage'];
}

module.exports = defaultConfig;
```
