### ISSUE TITLE
Puppetter npm instalation fails on CentOS 7.6

### ISSUE THREAD

**Issue by yami12376** [puppeteer/puppeteer#4326]
While doing steps from: https://jsreport.net/learn/centos using ansible
i have problem with puppeter.

Puppeteer version: 1.14.0
Platform / OS version: CentOS 7.6.1810
Node.js version: v8.11.3 (npm 5.6.0)
node -v
v8.11.3

Ansible steps:

```
---
- hosts: localhost
  vars:
    node_version: 8.11.3
    nvm_version: 0.33.11

  tasks:

    - name: install wget
      yum:
        name: wget
        state: latest

    - name: download nvm
      get_url:
        url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
        dest: /opt/nvm-install.sh

    - name: Changing perm of "/opt/nvm-install.sh", adding "+x"
      file:
        dest: /opt/nvm-install.sh
        mode: "a+x"

    - name: Execute the script
      command: /opt/nvm-install.sh
      args:
        creates: ~/.nvm/nvm.sh

    - name: Changing perm of "~/.nvm/nvm.sh", adding "+x"
      file:
        dest: ~/.nvm/nvm.sh
        mode: "a+x"

    - name: install node
      shell: |
        . ~/.nvm/nvm.sh
        nvm install {{ node_version }}
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}"

    - name: install jsreport-cli
      shell: |
        . ~/.nvm/nvm.sh
        npm install jsreport-cli -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/jsreport-cli"
        
    - name: install puppeteer 
      shell: |
        . ~/.nvm/nvm.sh
        npm install puppeteer  -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/puppeteer "        
        
    - name: install jsreport-chrome-pdf
      shell: |
        . ~/.nvm/nvm.sh
        npm install jsreport-chrome-pdf -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/jsreport-chrome-pdf"            

    - name: create jsreportapp directory
      file:
        path: ./jsreportapp
        state: directory

    - name: init jsreportapp directory
      shell: |
        . ~/.nvm/nvm.sh
        jsreport init
      args:
        chdir: ./jsreportapp
        creates: ./package-lock.json
```

Starting playbook with sudo on CentOS 7.6.
I get an error on step 

> install puppeteer

> 

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": ". ~/.nvm/nvm.sh\n npm install puppeteer -g", "delta": "0:00:04.038035", "end": "2019-04-23 11:29:56.050625", "msg": "non-zero return code", "rc": 1, "start": "2019-04-23 11:29:52.012590", "stderr": "sh: node: command not found\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! puppeteer@1.14.0 install: `node install.js`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the puppeteer@1.14.0 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2019-04-23T09_29_56_035Z-debug.log", "stderr_lines": ["sh: node: command not found", "npm ERR! file sh", "npm ERR! code ELIFECYCLE", "npm ERR! errno ENOENT", "npm ERR! syscall spawn", "npm ERR! puppeteer@1.14.0 install: `node install.js`", "npm ERR! spawn ENOENT", "npm ERR! ", "npm ERR! Failed at the puppeteer@1.14.0 install script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /root/.npm/_logs/2019-04-23T09_29_56_035Z-debug.log"], "stdout": "\n> puppeteer@1.14.0 install /root/.nvm/versions/node/v8.11.3/lib/node_modules/puppeteer\n> node install.js", "stdout_lines": ["", "> puppeteer@1.14.0 install /root/.nvm/versions/node/v8.11.3/lib/node_modules/puppeteer", "> node install.js"]}

But previous npm package is installed correctly.
