### ISSUE TITLE
Add install scripts for Chromium dependencies

### ISSUE THREAD

**Issue by remcohaszing** [puppeteer/puppeteer#4586]
In the [troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) document there are:

- A list of Debian packages required to run Chrome
- A list of CentOS packages required to run Chrome
- Instructions for running Puppeteer in Docker, which involves installing Google Chrome manually first.

This means the list of dependencies is managed in the Puppeteer documentation, and duplicated in any projects that use Puppeteer, e.g. in CI.

I suggest to add a simple shell script that prepares a Linux environment. This shell script will detect the package manager (`apt-get`, `yum`, or `apk`) and install required dependencies. This is especially useful for CI environments.

A CI job (GitLab CI example) using Puppeteer would look like this:

```yaml
test:
  image: node:10-slim
  script:
    - yarn --frozen-lockfile
    - yarn install-chrome-dependencies
    - yarn test
```

It should not be a post install script, since users will typically already have the dependencies installed on their development machines and the script requires root permissions.
