### ISSUE TITLE
libdbus-1.so.3: no version information available

### ISSUE THREAD

**Issue by swebal** [puppeteer/puppeteer#5379]
After installing puppeteer on AWS Elastic Beanstalk in a number of different ways such as via an ebextention script: [here](https://gist.github.com/chimmelb/6342504893b2b9fce0f4a8efd096ae60) or a shell script: [here](https://medium.com/@achillesmoraites/a-developers-guide-to-run-puppeteer-on-elastic-beanstalk-linux-no-ubuntu-linux-d137fa2641ae) , invoking a new browser always fails. I've tried a number of different launch options such as headless mode true/false, no sandbox, executable path etc.

When I run the following command: 

`ldd chrome | grep not`

I get the following response, which is always what follows a failed launch:

```
./chrome: /lib64/libdbus-1.so.3: no version information available (required by /usr/lib64/libatk-bridge-2.0.so.0)
./chrome: /lib64/libdbus-1.so.3: no version information available (required by /usr/lib64/libatspi.so.0)
```

Also, from the log on elastic beanstalk, it spits out afterwards:

`/var/app/current/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: symbol lookup error: /var/app/current/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: undefined symbol: g_type_class_adjust_private_offset`

I have no problems running puppeteer on my local mac os x, but Amazon Linux will not cooperate (as usual).

I should also mention that I've tried it on both load balanced and single instance, installation via script or manual via ssh. Always the same issue.

It's probably dead simple. I just don't speak Linux. Please help :(

**Comment by ankorGH** [comment]
current facing same issue, has anyone been able to resolve this.

**Comment by mathias-mcb** [comment]
Our recent deployment on AWS Elastic Beanstalk led to the same error/issue. The previous version that we deployed 20 days ago was working just as normal. 

Looks like the EB environment changed recently.

**Comment by eyeb14ck** [comment]
Run into the same issue. Fixed it by rolling back to v2.0.0 of Puppeteer. Seems like there's problems with new Puppeter update from 21d ago. Hope it will be fixed.

**Comment by dyatko** [comment]
Same here

**Comment by rebeccadavidsson** [comment]
Thanks, worked! 
`npm install puppeteer@2.0.0`

**Comment by liveme** [comment]
It doesn't work for me by back to puppeteer@2.0.0, why? Somebody can help? 
System: CentOS release 6.7 (Final)

**Comment by Memogcia** [comment]
Same here as liveme, could someone share if there is special configuration like for example in .ebextensions/chromiumpackages.config or share your puppeteer configuration, I am usign a Amazon Linux AMI

**Comment by MDwyer1157** [comment]
I was following instructions from this blog:
https://aws.amazon.com/blogs/devops/how-to-run-headless-front-end-tests-with-aws-cloud9-and-aws-codebuild/

and ran into the same issue. I also tried a "universal installer" script that I found here:
https://intoli.com/blog/installing-google-chrome-on-centos/

... but that didn't fix anything either.

Simply re-installing puppeteer after all that crazy allowed it to work for me. I ran this as suggested above, and it finally worked (thanks rebeccadavidson!!!):

npm install puppeteer@2.0.0

I might try again in a brand new/clean Cloud9 later this week to make sure it's repeatable.

**Comment by MDwyer1157** [comment]
Also, forgot to mention, that I had to adjust the paths when following the instructions from the AWS blog... here's the script as I ran it, after going to 
http://mirror.centos.org/centos/7/os/x86_64/Packages/ 

and 

http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages

to look up the changes for the paths.

**Note: Please remember that this alone did NOT fix the issue for me. As I noted above, I need to reinstall Puppeteer 2.0.0**

`sudo rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-1.el7.x86_64.rpm
sudo rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm
sudo rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-client-1.2.0-3.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-cursor-1.2.0-3.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm
sudo rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm
`

**Comment by lucasbretana** [comment]
Hi,
I'm also facing the same issue on AWS Elastic Beanstalk with Amazon Linux 2018.03 and Puppeteer@2.0.0,
The solution didn't seems to work for me, but I do have a sort of recommendation for those who got it working,
Make an AMI of the working instance and use it as base image to launch the instance on every deploy. You'll get stuck with puppeteer and dependencies on that version, but at least it will work until he have a real solution for the problem.
Also, just let me say this, Amazon Linux **sucks**.

**Comment by lmarques6** [comment]
Facing the same issue on AWS Elastic Beanstalk, bringing it down to puppeteer@2.0.0 worked for me!

**Comment by Johnsonzhangc** [comment]
> Hi,
> I'm also facing the same issue on AWS Elastic Beanstalk with Amazon Linux 2018.03 and Puppeteer@2.0.0,
> The solution didn't seems to work for me, but I do have a sort of recommendation for those who got it working,
> Make an AMI of the working instance and use it as base image to launch the instance on every deploy. You'll get stuck with puppeteer and dependencies on that version, but at least it will work until he have a real solution for the problem.
> Also, just let me say this, Amazon Linux **sucks**.

Rollback to 2.0.0 didn't work for me as well. Did you find any solution yet?

**Comment by richzw** [comment]
same issue here

**Comment by oslanier** [comment]
same issue

**Comment by TianqiGeng** [comment]
same issue

**Comment by wwwhatley** [comment]
Why was this closed when so many people are having the same issue....?

**Comment by wwwhatley** [comment]
Same issue

**Comment by sschilli** [comment]
I have experienced the same thing as well.

**Comment by wwwhatley** [comment]
I was able to fix my instance of the issue... I'm running on Ubuntu 18.04 and I had to download `google-chrome-stable` and then add an `executablePath` argument to `launch()` config.

1. Install google-chrome-stable on your Ubuntu instance -- 
`$ wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`
`$ sudo dpkg -i google-chrome*`

2. Install unmet dependencies -- 
`sudo apt-get install -f`

3. Add executablePath --

`  puppeteer.launch({
    executablePath: '/usr/bin/google-chrome-stable',
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']
  });`

**Comment by tiagotozi** [comment]
the same issue here using Firebase Functions.

**Comment by adamtaylor13** [comment]
I was really skeptical that simply downgrading would help, but as @MDwyer1157 mentioned, downgrading to version 2.0.0 finally worked for me.

However, _I too went through ALL the steps including running the installation script from intoli.com_. I'm not sure downgrading by itself would've resolved it.

If you tried _just_ downgrading, maybe try to also run that installation script, then run `ldd chrome | grep not` if you need to see what's left.

**Comment by SebC99** [comment]
Hello,
I just discovered this thread. In my case, I successfully run puppeteer 3.1.0 on elastic beanstalk with the following configuration script in the `.ebextensions` folder:
```
packages:
  yum:
    cups-libs: []
    dbus-glib: []
    libXrandr: []
    libXcursor: []
    libXinerama: []
    cairo: []
    cairo-gobject: []
    pango: []

commands:
  atk:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-2.el7.x86_64.rpm
  at-spi2-atk:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm
  at-spi2-core:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm
  GConf2:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/GConf2-3.2.6-8.el7.x86_64.rpm
  libXScrnSaver:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libXScrnSaver-1.2.2-6.1.el7.x86_64.rpm
  libxkbcommon:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libxkbcommon-0.7.1-3.el7.x86_64.rpm
  libwayland-client:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-client-1.15.0-1.el7.x86_64.rpm
  libwayland-cursor:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-cursor-1.15.0-1.el7.x86_64.rpm
  gtk3:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/gtk3-3.22.30-5.el7.x86_64.rpm
  gdk-pixbuf2:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/gdk-pixbuf2-2.36.12-3.el7.x86_64.rpm
```

Hope it helps

**Comment by dasheck0** [comment]
@wwwhatley This will only work if you have auto scaling disabled. EB throws away instances when auto scaling and therefore all manually installed dependencies are gone. You can create an AMI and use this for created instances for your EB application. But for small projects with only a single instance, that is never recycled this should work.

**Comment by gsogol** [comment]
@dasheck0 are you saying anything under .ebextensions (all underlying configs) is never executed when autoscaling is enabled (which is majority of deployments) for all the new instances?

**Comment by swebal** [comment]
Still doesn't work. Tried puppeteer v.2.0.0, v.2.1.0, v.3.1.0, v.3.3.0, always the same error:

Failed to launch the browser process!
/var/app/current/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: /lib64/libdbus-1.so.3: no version information available (required by /usr/lib64/libatk-bridge-2.0.so.0)
/var/app/current/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: /lib64/libdbus-1.so.3: no version information available (required by /usr/lib64/libatspi.so.0)
/var/app/current/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: symbol lookup error: /var/app/current/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: undefined symbol: g_type_class_adjust_private_offset

Anyone have any other ideas?

**Comment by SebC99** [comment]
@swebal have you tried my configuration?

**Comment by swebal** [comment]
This is my install script:

```
packages:
  yum:
    cups-libs: []
    dbus-glib: []
    dbus-libs: []
    libXrandr: []
    libXcursor: []
    libXdamage: []
    libXinerama: []
    cairo: []
    cairo-gobject: []
    pango: []

commands:
  atk:
    command: rpm -ivh --nodeps --replacepkgs --replacefiles http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-2.el7.x86_64.rpm
  at-spi2-atk:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm
  at-spi2-core:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm
  libgbm:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libgbm-18.3.4-7.el7.x86_64.rpm
  libwayland-server:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-server-1.15.0-1.el7.x86_64.rpm
  libdbus:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/dbus-libs-1.10.24-13.el7_6.x86_64.rpm
  GConf2:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm
  libXScrnSaver:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm
  libxkbcommon:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm
  libwayland-client:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-client-1.2.0-3.fc20.x86_64.rpm
  libwayland-cursor:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-cursor-1.2.0-3.fc20.x86_64.rpm
  gtk3:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm
  gdk-pixbuf2:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm
```

**Comment by SebC99** [comment]
You should try to update to mine as fedora archive are not working properly. Plus, the `nosignature` helped too

**Comment by swebal** [comment]
Tried yours, same error. Always missing libdbus-1.so.3, even though I'm adding it with:

`dbus-libs: []`

as well as:

```
libdbus:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/dbus-libs-1.10.24-13.el7_6.x86_64.rpm
```

**Comment by Funminiyi-debug** [comment]
what platform are you deploying it to? If it's heroku, puppeteer has a special configuration for those

**Comment by swebal** [comment]
AWS Elastic Beanstalk via Bitbucket pipeline (but uploading archive yields same error). I've tried different node and platform versions. I choose different instance types now and then to get a fresh start and sometimes that produces other errors for missing libs, such as libepoxy, libwayland-egl, libpng 1.5 & libpng12. I add the missing libs and somehow always end up with the same missing libdbus error.

**Comment by swebal** [comment]
Finally seems to be working on AWS Load Balanced environment. Puppeteer 2.0.0 and the following install script via ebextensions:

```
packages:
  yum:
    cups-libs: []
    dbus-glib: []
    libXrandr: []
    libXcursor: []
    libXinerama: []
    libepoxy: []
    cairo: []
    cairo-gobject: []
    pango: []

commands:
  atk:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-2.el7.x86_64.rpm
  at-spi2-atk:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm
  at-spi2-core:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm
  GConf2:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/GConf2-3.2.6-8.el7.x86_64.rpm
  libXScrnSaver:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libXScrnSaver-1.2.2-6.1.el7.x86_64.rpm
  libxkbcommon:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libxkbcommon-0.7.1-3.el7.x86_64.rpm
  libwayland-client:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-client-1.15.0-1.el7.x86_64.rpm
  libwayland-cursor:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-cursor-1.15.0-1.el7.x86_64.rpm
  libwayland-egl:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-egl-1.15.0-1.el7.x86_64.rpm
  libpng:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libpng-1.5.13-7.el7_2.x86_64.rpm
  libpng12:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libpng12-1.2.50-10.el7.x86_64.rpm
  gtk3:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/gtk3-3.22.30-5.el7.x86_64.rpm
  gdk-pixbuf2:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/gdk-pixbuf2-2.36.12-3.el7.x86_64.rpm
```

**Comment by hkurma** [comment]
@swebal You saved some time and stress for me. Thank you

I don't like downgrading the package and using it, but i don't seem to have a quick way and patience to fix this now. Thank again

**Comment by hkurma** [comment]
Adding to my previous comment, We are running our application on a scalable environment under AWS Elastic Beanstalk and i expect it to be seamless. Adding these bunch of commands via eb config is a pain and on top of that downgrading the package is worse.

**Comment by swengle** [comment]
I have puppeteer ^5.2.1 running on my beanstalk instances (Amazon Linux 2), used the following...

```
packages:
  yum:
    cups-libs: []
    dbus-glib: []
    libXrandr: []
    libXcursor: []
    libXinerama: []
    cairo: []
    cairo-gobject: []
    pango: []
    libXi: []
    libXcomposite: []
    libXtst: []
    alsa-lib-devel: []

commands:
  atk:
    command: rpm -ivh --nodeps --replacepkgs --replacefiles http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-2.el7.x86_64.rpm
  at-spi2-atk:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm
  at-spi2-core:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm
  libpng12:
    command: rpm -ivh --nodeps --replacepkgs http://mirror.centos.org/centos/7/os/x86_64/Packages/libpng12-1.2.50-10.el7.x86_64.rpm
  GConf2:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm
  libXScrnSaver:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm
  libxkbcommon:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm
  libwayland-cursor:
    command: rpm -Uvh --nodeps --replacepkgs --nosignature http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-cursor-1.15.0-1.el7.x86_64.rpm
  gtk3:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm
  gdk-pixbuf2:
    command: rpm -ivh --nodeps --replacepkgs http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm
    
```
