### ISSUE TITLE
Desktop fullpage screenshots are rendered as on the tablet view for a certain page element

### ISSUE THREAD

**Issue by roma-glushko** [puppeteer/puppeteer#5432]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: macOS Mojave 10.14.6 (18G103)
* Node.js version: v12.14.1

**What steps will reproduce the problem?**

A page with the main menu that has a different view on the mobile, tablet and desktop screens. Here is the view for the desktop view:
![2020-02-18_11-31-04](https://user-images.githubusercontent.com/9402690/74722774-2a58c000-5242-11ea-8b03-d63a6fc11d41.png)

The tablet view:
![2020-02-18_11-30-35](https://user-images.githubusercontent.com/9402690/74722722-1614c300-5242-11ea-9607-87706165804a.png)

The difference is that the label under the icons is hidden on the tablet devices. It's done by the following styling:

```css
@media all and (min-width: (769px)) and (max-width: 992px),
        all and (min-width: (769px)) and (orientation: portrait) {
        span:not(.ui-icon) {
            display: none;
        }
    }
}
```

The screenshots are taken by [BackstopJs](https://github.com/garris/BackstopJS) which is using Puppeteer under the hood.

**What is the expected result?**

I want to see the menu with icons and labels on the desktop screens (1024x1000 or 1440x1000 screens):

![2020-02-18_11-31-04](https://user-images.githubusercontent.com/9402690/74722774-2a58c000-5242-11ea-8b03-d63a6fc11d41.png)

**What happens instead?**

During `page.screenshot({fullPage: true})`, Puppeteer takes a screenshot with 1024x1000 and 1440x1000 resolutions, but the menu looks like on the tablet for some reason:

![2020-02-18_11-30-35](https://user-images.githubusercontent.com/9402690/74722722-1614c300-5242-11ea-9607-87706165804a.png)

Please let me know if you have any question or clarification to help here.
