### ISSUE TITLE
Docker: Error: net::ERR_CONNECTION_REFUSED at https

### ISSUE THREAD

**Issue by daddydrac** [puppeteer/puppeteer#5548]
It works outside of docker when trying to acess a local https site. But once containerized, returns the following:

```
Err Error: net::ERR_CONNECTION_REFUSED at https://127.0.0.1:443
    at navigate (/app/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/app/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/app/index.js:24:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by t1a2l** [comment]
@jschfflr - Hey facing this issue with https and http with localhost and 127.0.0.1 any solution? i am on version 11 on windows 10. on linux i have no issues.

**Comment by aktiver** [comment]
Get the NIC card address, it’s 10.0.0.1 I think.

**Comment by t1a2l** [comment]
@aktiver - how do i get it?

**Comment by daddydrac** [comment]
maybe ->
https://stackoverflow.com/questions/3837069/how-to-get-network-interface-card-names-in-python

**Comment by t1a2l** [comment]
How is that connected to the localhost i am using to connect to the pupeeter tests?

**Comment by daddydrac** [comment]
The NIC card thing works but also insecure, so may not work everywhere you try it. You could try the docker service name by putting puppeteer on same custom docker network called ```api_bridge```. I think thats how i solved it approx 2y ago:

```
 backend: # Docker service name
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - ./services/backend:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=XXXXXXXXXXX
      - DATABASE_TEST_URL=XXXXXXXXXX
      - SECRET_KEY=my_precious
    depends_on:
      - db
    networks:
      - api_bridge
     
frontend:  # Docker service name
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend/ui:/app' #Puppeteer code here
      - '/app/node_modules'
    ports:
      - 3007:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://127.0.0.1:5001
      - FRONTEND_GATEWAY_URL=http://127.0.0.1:3007
    networks:
      - api_bridge

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - api_bridge

networks:
  api_bridge:
    driver: bridge
```

So based on this networking scheme, you'd access as the docker services names:

```https://backend:443```

```https://frontend:443```

*This also assumes you're using an NGINX proxy, obviously.
