### ISSUE TITLE
[Bug]: How to install chrome and what path to put in executable path so that it launches chrome when in headless :false mode?

### ISSUE THREAD

**Issue by pankhiprasher** [puppeteer/puppeteer#8149]
### Bug description

Steps to reproduce the problem:

1. …
Cant seem to install chrome and hence getting this error - 
Error: Failed to launch the browser process!
[200202:200202:0318/231506.919330:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
[200202:200202:0318/231506.919374:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.

what should be in executable path to launch chrome as soon as function runs.

### Puppeteer version

13.5.2

### Node.js version

17.0.0

### npm version

8.5.2

### What operating system are you seeing the problem on?

Linux

**Comment by karl-cardenas-coding** [comment]
I am also getting this error.  Everything works fine locally but it crashes with the same error when ran inside a GitHub Actions pipeline.


Here are my configurations. 

```
# steps.js
const initBrowser = async() => {
  let browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    executablePath: process.env.CI === true ? process.env.PUPPETEER_EXEC_PATH : "",
    headless: false,
    devtools: false
  });

```
test.yaml
```
name: test
on:
  push:
    branches-ignore:
    - main
jobs:
  ui-test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Caching nodeJS
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: install puppeteer libraries
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgbm1
      #     sudo sysctl -w kernel.unprivileged_userns_clone=1

      - run: npm install --ignore-scripts

      # - name: Puppeteer Enablement
      #   uses: mujo-code/puppeteer-headful@v2

      - name: End to End Test
        run: npm run test-e2e

```

**Comment by karl-cardenas-coding** [comment]
@pankhiprasher I got it to work in GitHub Actions. Here is what the new YAML is

```
name: test
on:
  push:
    branches-ignore:
    - main
jobs:
  ui-test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Caching nodeJS
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install --ignore-scripts

      - name: End to End Test
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          npm run test-e2e
```
