### ISSUE TITLE
[Bug]: CircleCi - [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/node/install.js' is not defined by "exports" in /root/project/node_modules/puppeteer/package.json imported from /root/project/node_modules/puppeteer/install.js

### ISSUE THREAD

**Issue by valentinprivasee** [puppeteer/puppeteer#9224]
### Bug description

Steps to reproduce the problem:

1. Do npm install npm i puppeteer@19.2.2
3. Attempt to do npm install with cypress/install **workflow** from my **circle ci** will run it will throw an error (I attached the log below):

``` 
- cypress/install:
                  install-command: npm install && npm install --prefix front-end
                  requires:
                      - build
                      - check-builds-on-aws
                  filters:
                      branches:
                          only:
                              - master
                              - dev```
will output this result as an error:

``````

This error can be fixed by using puppeteer@18.2.1 or v16 (I tried with those)

On Windows & Mac. that version works just fine, but I think is something related to Linux environment that's cracking.

### Puppeteer version

puppeteer@19.2.2

### Node.js version

- image: circleci/node:16.13

### npm version

Latest

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/node/install.js' is not defined by "exports" in /root/project/node_modules/puppeteer/package.json imported from /root/project/node_modules/puppeteer/install.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at trySelf (internal/modules/cjs/loader.js:420:34)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:809:24)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/project/node_modules/puppeteer/install.js:38:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
